name: tart_dev
description: "Tiny Dart."
version: 0.0.2
homepage: https://github.com/hatcha6/tart

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  coverage: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
